export default defineEventHandler(() => {
  return [
    {
      model: 'GW-S22-6',
      primeKW: 16,
      primeKVA: 20,
      standbyKW: 18,
      standbyKVA: 22,
      engine: '4Z2.3-G21',
      cylinder: '4L/NA',
      speedGovernor: 'E',
      displacement: 2.3,
      cons: 4.7,
      emission: 'N/A',
    },
    {
      model: 'GW-S28-6',
      primeKW: 20,
      primeKVA: 25,
      standbyKW: 22,
      standbyKVA: 28,
      engine: '4Z2.7-G21',
      cylinder: '4L/NA',
      speedGovernor: 'E',
      displacement: 2.7,
      cons: 4.7,
      emission: 'N/A',
    },
    {
      model: 'GW-S33-6',
      primeKW: 24,
      primeKVA: 30,
      standbyKW: 26,
      standbyKVA: 33,
      engine: '4Z3.0-G21',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: 3,
      cons: 5.8,
      emission: 'N/A',
    },
    {
      model: 'GW-S41-6',
      primeKW: 30,
      primeKVA: 38,
      standbyKW: 33,
      standbyKVA: 41,
      engine: '4Z3.2-G21',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: 3.2,
      cons: 7.7,
      emission: 'N/A',
    },
    {
      model: 'GW-S47-6',
      primeKW: 34,
      primeKVA: 43,
      standbyKW: 37,
      standbyKVA: 47,
      engine: '4ZT3.2-G21',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: 3.2,
      cons: 9,
      emission: 'N/A',
    },
    {
      model: 'GW-S66-6',
      primeKW: 48,
      primeKVA: 60,
      standbyKW: 53,
      standbyKVA: 66,
      engine: '4ZT3.5-G21',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: 3.5,
      cons: 11,
      emission: 'N/A',
    },
    {
      model: 'GW-S77-6',
      primeKW: 56,
      primeKVA: 70,
      standbyKW: 62,
      standbyKVA: 77,
      engine: '4ZT4.1-G21',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: 4.1,
      cons: 12.5,
      emission: 'N/A',
    },
    {
      model: 'GW-S83-6',
      primeKW: 60,
      primeKVA: 75,
      standbyKW: 66,
      standbyKVA: 83,
      engine: '4ZTAA4.1-G21',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: 4.1,
      cons: 12.8,
      emission: 'N/A',
    },
    {
      model: 'GW-S88-6',
      primeKW: 64,
      primeKVA: 80,
      standbyKW: 70,
      standbyKVA: 88,
      engine: '4ZTAA4.1-G22',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: 4.1,
      cons: 12.8,
      emission: 'N/A',
    },
    {
      model: 'GW-S94-6',
      primeKW: 68,
      primeKVA: 85,
      standbyKW: 75,
      standbyKVA: 94,
      engine: '4HT4.3-G23',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: 4.3,
      cons: 21.6,
      emission: 'N/A',
    },
    {
      model: 'GW-S120-6',
      primeKW: 88,
      primeKVA: 110,
      standbyKW: 97,
      standbyKVA: 120,
      engine: '4HTAA4.3-G21',
      cylinder: '4L/TCA',
      speedGovernor: 'E',
      displacement: 4.3,
      cons: 25.6,
      emission: 'N/A',
    },
    {
      model: 'GW-S138-6',
      primeKW: 100,
      primeKVA: 125,
      standbyKW: 110,
      standbyKVA: 138,
      engine: '4HTAA4.3-G23',
      cylinder: '4L/TCA',
      speedGovernor: 'E',
      displacement: 4.3,
      cons: 28.8,
      emission: 'N/A',
    },
    {
      model: 'GW-S165-6',
      primeKW: 120,
      primeKVA: 150,
      standbyKW: 132,
      standbyKVA: 165,
      engine: '6HTAA6.5-G21',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 6.5,
      cons: 33.1,
      emission: 'N/A',
    },
    {
      model: 'GW-S176-6',
      primeKW: 128,
      primeKVA: 160,
      standbyKW: 141,
      standbyKVA: 176,
      engine: '6HTAA6.5-G22',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 6.5,
      cons: 36.3,
      emission: 'N/A',
    },
    {
      model: 'GW-S220-6',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 176,
      standbyKVA: 220,
      engine: '6HTAA6.5-G23',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 6.5,
      cons: 43.4,
      emission: 'N/A',
    },
    {
      model: 'GW-S250-6',
      primeKW: 182,
      primeKVA: 228,
      standbyKW: 200,
      standbyKVA: 250,
      engine: '6DTAA8.9-G21',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.9,
      cons: 50.9,
      emission: 'N/A',
    },
    {
      model: 'GW-S275-6',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 220,
      standbyKVA: 275,
      engine: '6DTAA8.9-G24',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.9,
      cons: 50.9,
      emission: 'N/A',
    },
    {
      model: 'GW-S303-6',
      primeKW: 220,
      primeKVA: 275,
      standbyKW: 242,
      standbyKVA: 303,
      engine: '6DTAA8.9-G23',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.9,
      cons: 63,
      emission: 'N/A',
    },
    {
      model: 'GW-S385-6',
      primeKW: 280,
      primeKVA: 350,
      standbyKW: 308,
      standbyKVA: 385,
      engine: '6ETAA11.8-G22',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 11.8,
      cons: 73.7,
      emission: 'N/A',
    },
    {
      model: 'GW-S413-6',
      primeKW: 300,
      primeKVA: 375,
      standbyKW: 330,
      standbyKVA: 413,
      engine: '6ETAA12.8-G22',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 12.8,
      cons: 88.4,
      emission: 'N/A',
    },
    {
      model: 'GW-S440-6',
      primeKW: 320,
      primeKVA: 400,
      standbyKW: 352,
      standbyKVA: 440,
      engine: '6ETAA12.8-G21',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 12.8,
      cons: 88.4,
      emission: 'N/A',
    },
    {
      model: 'GW-S500-6',
      primeKW: 360,
      primeKVA: 450,
      standbyKW: 400,
      standbyKVA: 500,
      engine: '6ETAA12.8-G32',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 12.8,
      cons: 96.3,
      emission: 'N/A',
    },
    {
      model: 'GW-S550-6',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: '6ETAA12.8-G310.1',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 12.8,
      cons: 107.5,
      emission: 'N/A',
    },
    {
      model: 'GW-S619-6',
      primeKW: 450,
      primeKVA: 563,
      standbyKW: 495,
      standbyKVA: 619,
      engine: '6KTAA25-G311',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 25.2,
      cons: 127.4,
      emission: 'N/A',
    },
    {
      model: 'GW-S688-6',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 550,
      standbyKVA: 688,
      engine: '6KTAA25-G310',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 25.2,
      cons: 137.5,
      emission: 'N/A',
    },
    {
      model: 'GW-S770-6',
      primeKW: 560,
      primeKVA: 700,
      standbyKW: 616,
      standbyKVA: 770,
      engine: '6KTAA25-G39',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 25.2,
      cons: 149.9,
      emission: 'N/A',
    },
    {
      model: 'GW-S825-6',
      primeKW: 600,
      primeKVA: 750,
      standbyKW: 660,
      standbyKVA: 825,
      engine: '6KTAA25-G32.1',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 25.2,
      cons: 171.7,
      emission: 'N/A',
    },
    {
      model: 'GW-S900-6',
      primeKW: 660,
      primeKVA: 825,
      standbyKW: 726,
      standbyKVA: 900,
      engine: '6KTAA25-G31.1',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 25.2,
      cons: 182.8,
      emission: 'N/A',
    },
  ]
})
