export default defineEventHandler(() => {
  return [
    {
      model: 'GW-P10',
      primeKW: 7,
      primeKVA: 9,
      standbyKW: 8,
      standbyKVA: 10,
      engine: '403A-11G1',
      cylinder: '3L/NA',
      speedGovernor: 'M',
      displacement: '1.1 ',
      cons: '2.5 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P10',
      primeKW: 7,
      primeKVA: 9,
      standbyKW: 8,
      standbyKVA: 10,
      engine: '403D-11G',
      cylinder: '3L/NA',
      speedGovernor: 'M',
      displacement: '1.1 ',
      cons: '2.6 ',
      emission: 'T4I/EU ⅢA',
    },
    {
      model: 'GW-P13',
      primeKW: 10,
      primeKVA: 13,
      standbyKW: 11,
      standbyKVA: 14,
      engine: '403A-15G1',
      cylinder: '3L/NA',
      speedGovernor: 'M',
      displacement: '1.5 ',
      cons: '3.6 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P13',
      primeKW: 10,
      primeKVA: 13,
      standbyKW: 11,
      standbyKVA: 14,
      engine: '403D-15G',
      cylinder: '3L/NA',
      speedGovernor: 'M',
      displacement: '1.5 ',
      cons: '3.7 ',
      emission: 'T4I/EU ⅢA',
    },
    {
      model: 'GW-P17',
      primeKW: 12,
      primeKVA: 15,
      standbyKW: 13,
      standbyKVA: 17,
      engine: '403A-15G2',
      cylinder: '3L/NA',
      speedGovernor: 'M',
      displacement: '1.5 ',
      cons: '4.1 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P22',
      primeKW: 16,
      primeKVA: 20,
      standbyKW: 18,
      standbyKVA: 22,
      engine: '404A-22G1',
      cylinder: '4L/NA',
      speedGovernor: 'M',
      displacement: '2.2 ',
      cons: '5.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P22',
      primeKW: 16,
      primeKVA: 20,
      standbyKW: 18,
      standbyKVA: 22,
      engine: '404D-22G',
      cylinder: '4L/NA',
      speedGovernor: 'M',
      displacement: '2.2 ',
      cons: '5.4 ',
      emission: 'T4I/EU ⅢA',
    },
    {
      model: 'GW-P30',
      primeKW: 22,
      primeKVA: 28,
      standbyKW: 24,
      standbyKVA: 30,
      engine: '404D-22TG',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: '2.2 ',
      cons: '7.1 ',
      emission: 'T4I/EU ⅢA',
    },
    {
      model: 'GW-P33',
      primeKW: 24,
      primeKVA: 30,
      standbyKW: 26,
      standbyKVA: 33,
      engine: '1103A-33G',
      cylinder: '3L/NA',
      speedGovernor: 'M',
      displacement: '3.3 ',
      cons: '7.1 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P50',
      primeKW: 36,
      primeKVA: 45,
      standbyKW: 40,
      standbyKVA: 50,
      engine: '1103A-33TG1',
      cylinder: '3L/TC',
      speedGovernor: 'M',
      displacement: '3.3 ',
      cons: '10.7 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P66',
      primeKW: 48,
      primeKVA: 60,
      standbyKW: 53,
      standbyKVA: 66,
      engine: '1103A-33TG2',
      cylinder: '3L/TC',
      speedGovernor: 'M',
      displacement: '3.3 ',
      cons: '13.9 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P72',
      primeKW: 52,
      primeKVA: 65,
      standbyKW: 58,
      standbyKVA: 72,
      engine: '1104A-44TG1',
      cylinder: '4L/TC',
      speedGovernor: 'M',
      displacement: '4.4 ',
      cons: '14.8 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P88',
      primeKW: 64,
      primeKVA: 80,
      standbyKW: 70,
      standbyKVA: 88,
      engine: '1104A-44TG2',
      cylinder: '4L/TC',
      speedGovernor: 'M',
      displacement: '4.4 ',
      cons: '18.7 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P110',
      primeKW: 80,
      primeKVA: 100,
      standbyKW: 88,
      standbyKVA: 110,
      engine: '1104C-44TAG2',
      cylinder: '4L/TCA',
      speedGovernor: 'E',
      displacement: '4.4 ',
      cons: '22.6 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-P150',
      primeKW: 108,
      primeKVA: 135,
      standbyKW: 120,
      standbyKVA: 150,
      engine: '1106A-7OTG1',
      cylinder: '6L/TC',
      speedGovernor: 'M',
      displacement: '7.0 ',
      cons: '30.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P165',
      primeKW: 120,
      primeKVA: 150,
      standbyKW: 132,
      standbyKVA: 165,
      engine: '1106A-7OTAG2',
      cylinder: '6L/TCA',
      speedGovernor: 'M',
      displacement: '7.0 ',
      cons: '32.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P200',
      primeKW: 144,
      primeKVA: 180,
      standbyKW: 160,
      standbyKVA: 200,
      engine: '1106A-7OTAG3',
      cylinder: '6L/TCA',
      speedGovernor: 'M',
      displacement: '7.0 ',
      cons: '40.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P220',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 176,
      standbyKVA: 220,
      engine: '1106A-7OTAG4',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '7.0 ',
      cons: '44.7 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P250',
      primeKW: 180,
      primeKVA: 225,
      standbyKW: 200,
      standbyKVA: 250,
      engine: '1506A-E88TAG2',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '8.8 ',
      cons: '50.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P250',
      primeKW: 180,
      primeKVA: 225,
      standbyKW: 200,
      standbyKVA: 250,
      engine: '1206A-E7OTTAG2',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.0 ',
      cons: '51.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P275',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 220,
      standbyKVA: 275,
      engine: '1206A-E7OTTAG3',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.0 ',
      cons: '56.9 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P275',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 220,
      standbyKVA: 275,
      engine: '1506A-E88TAG3',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '8.8 ',
      cons: '56.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P339',
      primeKW: 240,
      primeKVA: 300,
      standbyKW: 271,
      standbyKVA: 339,
      engine: '1706A-E93TAG1',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '9.3 ',
      cons: '62.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P383',
      primeKW: 278,
      primeKVA: 348,
      standbyKW: 306,
      standbyKVA: 383,
      engine: '1706A-E93TAG2',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '9.3 ',
      cons: '70.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P400',
      primeKW: 280,
      primeKVA: 350,
      standbyKW: 320,
      standbyKVA: 400,
      engine: '2206C-E13TAG2',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.5 ',
      cons: '71.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-P450',
      primeKW: 320,
      primeKVA: 400,
      standbyKW: 360,
      standbyKVA: 450,
      engine: '2206C-E13TAG3',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.5 ',
      cons: '81.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-P500',
      primeKW: 360,
      primeKVA: 450,
      standbyKW: 400,
      standbyKVA: 500,
      engine: '2506C-E15TAG1',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '15.2 ',
      cons: '95.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-P550',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: '2506C-E15TAG2',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '15.2 ',
      cons: '106.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-P650',
      primeKW: 472,
      primeKVA: 590,
      standbyKW: 520,
      standbyKVA: 650,
      engine: '2806C-E18TAG1A',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '18.0 ',
      cons: '123.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-P700',
      primeKW: 520,
      primeKVA: 650,
      standbyKW: 560,
      standbyKVA: 700,
      engine: '2806A-E18TAG2',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '18.0 ',
      cons: '132.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P825',
      primeKW: 600,
      primeKVA: 750,
      standbyKW: 660,
      standbyKVA: 825,
      engine: '4006-23TAG2A',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '22.9 ',
      cons: '157.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P900',
      primeKW: 640,
      primeKVA: 800,
      standbyKW: 720,
      standbyKVA: 900,
      engine: '4006-23TAG3A',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '22.9 ',
      cons: '172.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P1000',
      primeKW: 720,
      primeKVA: 900,
      standbyKW: 800,
      standbyKVA: 1000,
      engine: '4008TAG1A',
      cylinder: '8L/TCA',
      speedGovernor: 'E',
      displacement: '30.6 ',
      cons: '212.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P1100',
      primeKW: 800,
      primeKVA: 1000,
      standbyKW: 880,
      standbyKVA: 1100,
      engine: '4008TAG2A',
      cylinder: '8L/TCA',
      speedGovernor: 'E',
      displacement: '30.6 ',
      cons: '220.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P1250',
      primeKW: 900,
      primeKVA: 1125,
      standbyKW: 1000,
      standbyKVA: 1250,
      engine: '4008-3OTAG3',
      cylinder: '8L/TCA',
      speedGovernor: 'E',
      displacement: '30.6 ',
      cons: '244.5 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P1385',
      primeKW: 1000,
      primeKVA: 1250,
      standbyKW: 1108,
      standbyKVA: 1385,
      engine: '4012-46TWG2A',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: '45.4 ',
      cons: '259.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P1600',
      primeKW: 1200,
      primeKVA: 1500,
      standbyKW: 1280,
      standbyKVA: 1600,
      engine: '4012-46TAG2A',
      cylinder: '12V/TCA',
      speedGovernor: 'E',
      displacement: '45.4 ',
      cons: '301.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P1815',
      primeKW: 1320,
      primeKVA: 1650,
      standbyKW: 1452,
      standbyKVA: 1815,
      engine: '4012-46TAG3A',
      cylinder: '12V/TCA',
      speedGovernor: 'E',
      displacement: '45.4 ',
      cons: '370.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P2000',
      primeKW: 1480,
      primeKVA: 1850,
      standbyKW: 1600,
      standbyKVA: 2000,
      engine: '4016TAG1A',
      cylinder: '16V/TCA',
      speedGovernor: 'E',
      displacement: '61.0 ',
      cons: '383.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P2250',
      primeKW: 1600,
      primeKVA: 2000,
      standbyKW: 1800,
      standbyKVA: 2250,
      engine: '4016TAG2A',
      cylinder: '16V/TCA',
      speedGovernor: 'E',
      displacement: '61.0 ',
      cons: '434.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-P2500',
      primeKW: 1800,
      primeKVA: 2250,
      standbyKW: 2000,
      standbyKVA: 2500,
      engine: '4016-61TRG3',
      cylinder: '16V/TW',
      speedGovernor: 'E',
      displacement: '61.0 ',
      cons: '473.0 ',
      emission: 'N/A',
    },
  ]
})
