export default defineEventHandler(() => {
  return [
    {
      model: 'GW-V95-6',
      primeKW: 69,
      primeKVA: 86,
      standbyKW: 76,
      standbyKVA: 95,
      engine: 'TAD53OGE',
      cylinder: '4L/TCA',
      speedGovernor: 'M',
      displacement: 4.8,
      cons: 20,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V110-6',
      primeKW: 80,
      primeKVA: 100,
      standbyKW: 88,
      standbyKVA: 110,
      engine: 'TAD531GE',
      cylinder: '4L/TCA',
      speedGovernor: 'M',
      displacement: 4.8,
      cons: 23,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V145-6',
      primeKW: 104,
      primeKVA: 130,
      standbyKW: 116,
      standbyKVA: 145,
      engine: 'TAD532GE',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: 4.8,
      cons: 31,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V176-6',
      primeKW: 128,
      primeKVA: 160,
      standbyKW: 141,
      standbyKVA: 176,
      engine: 'TAD731GE',
      cylinder: '6L/TCA',
      speedGovernor: 'M',
      displacement: 7.2,
      cons: 36,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V220-6',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 176,
      standbyKVA: 220,
      engine: 'TAD732GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 7.2,
      cons: 46,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V234-6',
      primeKW: 176,
      primeKVA: 220,
      standbyKW: 187,
      standbyKVA: 234,
      engine: 'TAD733GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 7.2,
      cons: 51,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V286-6',
      primeKW: 208,
      primeKVA: 260,
      standbyKW: 229,
      standbyKVA: 286,
      engine: 'TAD841GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 7.2,
      cons: 59,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V320-6',
      primeKW: 240,
      primeKVA: 300,
      standbyKW: 256,
      standbyKVA: 320,
      engine: 'TAD842GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 7.2,
      cons: 68,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V350-6',
      primeKW: 256,
      primeKVA: 320,
      standbyKW: 280,
      standbyKVA: 350,
      engine: 'TAD843GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 7.2,
      cons: 70,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V375-6',
      primeKW: 272,
      primeKVA: 340,
      standbyKW: 300,
      standbyKVA: 375,
      engine: 'TAD1341GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 12.8,
      cons: 71,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V440-6',
      primeKW: 320,
      primeKVA: 400,
      standbyKW: 352,
      standbyKVA: 440,
      engine: 'TAD1342GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 12.8,
      cons: 84,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V450-6',
      primeKW: 328,
      primeKVA: 410,
      standbyKW: 360,
      standbyKVA: 450,
      engine: 'TAD1343GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 12.8,
      cons: 93,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V500-6',
      primeKW: 360,
      primeKVA: 450,
      standbyKW: 400,
      standbyKVA: 500,
      engine: 'TAD1344GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 12.8,
      cons: 95,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V600-6',
      primeKW: 440,
      primeKVA: 550,
      standbyKW: 480,
      standbyKVA: 600,
      engine: 'TAD1641GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 16.1,
      cons: 120,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V688-6',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 550,
      standbyKVA: 688,
      engine: 'TAD1642GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 16.1,
      cons: 134,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V750-6',
      primeKW: 548,
      primeKVA: 685,
      standbyKW: 600,
      standbyKVA: 750,
      engine: 'TWD1644GE',
      cylinder: '6L/TW',
      speedGovernor: 'ECU',
      displacement: 16.1,
      cons: 144,
      emission: 'T2/EUⅡ',
    },
    {
      model: 'GW-V800-6',
      primeKW: 580,
      primeKVA: 725,
      standbyKW: 640,
      standbyKVA: 800,
      engine: 'TWD1645GE',
      cylinder: '6L/TW',
      speedGovernor: 'ECU',
      displacement: 16.1,
      cons: 149,
      emission: 'T2/EUⅡ',
    },
  ]
})
