export default defineEventHandler(() => {
  return [
    {
      model: 'GW-YD10',
      primeKW: 7,
      primeKVA: 9,
      standbyKW: 8,
      standbyKVA: 10,
      engine: 'YD380D',
      cylinder: '3L/NA',
      speedGovernor: 'M/E',
      displacement: '1.357 ',
      cons: '3.16 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD11',
      primeKW: 8,
      primeKVA: 10,
      standbyKW: 9,
      standbyKVA: 11,
      engine: 'YD385D',
      cylinder: '3L/NA',
      speedGovernor: 'M/E',
      displacement: '1.532 ',
      cons: '3.55 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD14',
      primeKW: 10,
      primeKVA: 13,
      standbyKW: 11,
      standbyKVA: 14,
      engine: 'YD480D',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '1.809 ',
      cons: '4.22 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD15',
      primeKW: 11,
      primeKVA: 14,
      standbyKW: 12,
      standbyKVA: 15,
      engine: 'YD4KD(YD485D)',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '2.156 ',
      cons: '4.71 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD17',
      primeKW: 12,
      primeKVA: 15,
      standbyKW: 13,
      standbyKVA: 17,
      engine: 'YND485D',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '2.156 ',
      cons: '4.77 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD21',
      primeKW: 15,
      primeKVA: 19,
      standbyKW: 17,
      standbyKVA: 21,
      engine: 'YND490D',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '2.540 ',
      cons: '4.83 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD22',
      primeKW: 16,
      primeKVA: 20,
      standbyKW: 18,
      standbyKVA: 22,
      engine: 'YSD490D',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '2.540 ',
      cons: '5.45 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD25',
      primeKW: 18,
      primeKVA: 23,
      standbyKW: 20,
      standbyKVA: 25,
      engine: 'Y490D-P',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '2.670 ',
      cons: '6.43 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD28',
      primeKW: 20,
      primeKVA: 25,
      standbyKW: 22,
      standbyKVA: 28,
      engine: 'Y495D',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '2.977 ',
      cons: '6.87 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD30',
      primeKW: 22,
      primeKVA: 28,
      standbyKW: 24,
      standbyKVA: 30,
      engine: 'Y4100D',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '3.707 ',
      cons: '7.05 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD33',
      primeKW: 24,
      primeKVA: 30,
      standbyKW: 26,
      standbyKVA: 33,
      engine: 'Y4102D',
      cylinder: '4L/NA',
      speedGovernor: 'M/E',
      displacement: '3.875 ',
      cons: '8.94 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD40',
      primeKW: 29,
      primeKVA: 36,
      standbyKW: 32,
      standbyKVA: 40,
      engine: 'Y4105D',
      cylinder: '4L/TC',
      speedGovernor: 'M/E',
      displacement: '4.087 ',
      cons: '8.80 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD41',
      primeKW: 30,
      primeKVA: 38,
      standbyKW: 33,
      standbyKVA: 41,
      engine: 'Y4102ZD',
      cylinder: '4L/TC',
      speedGovernor: 'M/E',
      displacement: '3.875 ',
      cons: '8.94 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD50',
      primeKW: 36,
      primeKVA: 45,
      standbyKW: 40,
      standbyKVA: 50,
      engine: 'Y4102ZLD',
      cylinder: '4L/TC',
      speedGovernor: 'M/E',
      displacement: '3.875 ',
      cons: '13.16 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD55',
      primeKW: 40,
      primeKVA: 50,
      standbyKW: 44,
      standbyKVA: 55,
      engine: 'Y4105ZLD',
      cylinder: '4L/TC',
      speedGovernor: 'M/E',
      displacement: '4.087 ',
      cons: '14.72 ',
      emission: 'N/A',
    },
    {
      model: 'GW-YD66',
      primeKW: 48,
      primeKVA: 60,
      standbyKW: 53,
      standbyKVA: 66,
      engine: 'YD4EZLD',
      cylinder: '4L/TC',
      speedGovernor: 'M/E',
      displacement: '4.087 ',
      cons: '16.87 ',
      emission: 'N/A',
    },
  ]
})
