export default defineEventHandler(() => {
  return [
    {
      model: 'GW-V93',
      primeKW: 68,
      primeKVA: 85,
      standbyKW: 74,
      standbyKVA: 93,
      engine: 'TAD530GE',
      cylinder: '4L/TCA',
      speedGovernor: 'M',
      displacement: '4.76 ',
      cons: '19.3 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V110',
      primeKW: 80,
      primeKVA: 100,
      standbyKW: 88,
      standbyKVA: 110,
      engine: 'TAD531GE',
      cylinder: '4L/TCA',
      speedGovernor: 'M',
      displacement: '4.76 ',
      cons: '22.8 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V138',
      primeKW: 100,
      primeKVA: 125,
      standbyKW: 110,
      standbyKVA: 138,
      engine: 'TAD532GE',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '4.76 ',
      cons: '28.6 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V165',
      primeKW: 120,
      primeKVA: 150,
      standbyKW: 132,
      standbyKVA: 165,
      engine: 'TAD731GE',
      cylinder: '6L/TCA',
      speedGovernor: 'M',
      displacement: '7.15 ',
      cons: '32.9 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V200',
      primeKW: 144,
      primeKVA: 180,
      standbyKW: 160,
      standbyKVA: 200,
      engine: 'TAD732GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.15 ',
      cons: '40.3 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V220',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 176,
      standbyKVA: 220,
      engine: 'TAD733GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.15 ',
      cons: '43.6 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V275',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 220,
      standbyKVA: 275,
      engine: 'TAD734GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.15 ',
      cons: '51.8 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V343',
      primeKW: 250,
      primeKVA: 313,
      standbyKW: 275,
      standbyKVA: 343,
      engine: 'TAD1341GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '68.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V385',
      primeKW: 280,
      primeKVA: 350,
      standbyKW: 308,
      standbyKVA: 385,
      engine: 'TAD1342GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '71.6 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V413',
      primeKW: 300,
      primeKVA: 375,
      standbyKW: 330,
      standbyKVA: 413,
      engine: 'TAD1343GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '73.6 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V440',
      primeKW: 320,
      primeKVA: 400,
      standbyKW: 352,
      standbyKVA: 440,
      engine: 'TAD1344GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '80.2 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V500',
      primeKW: 360,
      primeKVA: 450,
      standbyKW: 400,
      standbyKVA: 500,
      engine: 'TAD1345GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '88.5 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V550',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: 'TAD1346GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '97.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V550',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: 'TAD1641GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '16.12 ',
      cons: '100.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V625',
      primeKW: 456,
      primeKVA: 570,
      standbyKW: 500,
      standbyKVA: 625,
      engine: 'TAD1642GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '16.12 ',
      cons: '113.7 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V700',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 560,
      standbyKVA: 700,
      engine: 'TWD1644GE',
      cylinder: '6L/TW',
      speedGovernor: 'ECU',
      displacement: '16.12 ',
      cons: '126.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V770',
      primeKW: 560,
      primeKVA: 700,
      standbyKW: 616,
      standbyKVA: 770,
      engine: 'TWD1645GE',
      cylinder: '6L/TW',
      speedGovernor: 'ECU',
      displacement: '16.12 ',
      cons: '139.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-V107',
      primeKW: 80,
      primeKVA: 100,
      standbyKW: 86,
      standbyKVA: 107,
      engine: 'TAD58OVE',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '5.13 ',
      cons: '20.4 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V125',
      primeKW: 92,
      primeKVA: 115,
      standbyKW: 100,
      standbyKVA: 125,
      engine: 'TAD581VE',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '5.13 ',
      cons: '24.8 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V147',
      primeKW: 108,
      primeKVA: 135,
      standbyKW: 118,
      standbyKVA: 147,
      engine: 'TAD582VE',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '5.13 ',
      cons: '28.0 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V165',
      primeKW: 120,
      primeKVA: 150,
      standbyKW: 132,
      standbyKVA: 165,
      engine: 'TAD88OGE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.7 ',
      cons: '30.0 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V220',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 176,
      standbyKVA: 220,
      engine: 'TAD881GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.7 ',
      cons: '40.0 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V275',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 220,
      standbyKVA: 275,
      engine: 'TAD882GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.7 ',
      cons: '50.7 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V330',
      primeKW: 240,
      primeKVA: 300,
      standbyKW: 264,
      standbyKVA: 330,
      engine: 'TAD1380GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '60.7 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V385',
      primeKW: 280,
      primeKVA: 350,
      standbyKW: 308,
      standbyKVA: 385,
      engine: 'TAD1381GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '71.0 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V440',
      primeKW: 320,
      primeKVA: 400,
      standbyKW: 352,
      standbyKVA: 440,
      engine: 'TAD1382GE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '12.78 ',
      cons: '80.1 ',
      emission: 'EU V',
    },
    {
      model: 'GW-V737',
      primeKW: 536,
      primeKVA: 670,
      standbyKW: 589,
      standbyKVA: 737,
      engine: 'TWD1683GE',
      cylinder: '6L/TW',
      speedGovernor: 'ECU',
      displacement: '16.12 ',
      cons: '130.0 ',
      emission: 'EU V',
    },
  ]
})
