export default defineEventHandler(() => {
  return [
    {
      model: 'GW-H180-6',
      primeKW: 134,
      primeKVA: 168,
      standbyKW: 144,
      standbyKVA: 180,
      engine: 'DP086TA',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.1,
      cons: 41.3,
      emission: 'N/A',
    },
    {
      model: 'GW-H200-6',
      primeKW: 144,
      primeKVA: 180,
      standbyKW: 160,
      standbyKVA: 200,
      engine: 'DPO86TA',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.1,
      cons: 41.3,
      emission: 'N/A',
    },
    {
      model: 'GW-H209-6',
      primeKW: 152,
      primeKVA: 190,
      standbyKW: 167,
      standbyKVA: 209,
      engine: 'PO86TI-1',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.1,
      cons: 42.4,
      emission: 'N/A',
    },
    {
      model: 'GW-H230-6',
      primeKW: 168,
      primeKVA: 210,
      standbyKW: 184,
      standbyKVA: 230,
      engine: 'PO86TI',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.1,
      cons: 50.6,
      emission: 'N/A',
    },
    {
      model: 'GW-H250-6',
      primeKW: 183,
      primeKVA: 228,
      standbyKW: 200,
      standbyKVA: 250,
      engine: 'PO86TI',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.1,
      cons: 50.6,
      emission: 'N/A',
    },
    {
      model: 'GW-H285-6',
      primeKW: 204,
      primeKVA: 256,
      standbyKW: 228,
      standbyKVA: 285,
      engine: 'DPO86LA',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.1,
      cons: 56,
      emission: 'N/A',
    },
    {
      model: 'GW-H320-6',
      primeKW: 240,
      primeKVA: 300,
      standbyKW: 256,
      standbyKVA: 320,
      engine: 'P126TI',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 11.1,
      cons: 70.3,
      emission: 'N/A',
    },
    {
      model: 'GW-H375-6',
      primeKW: 275,
      primeKVA: 344,
      standbyKW: 300,
      standbyKVA: 375,
      engine: 'P126TI-II',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 11.1,
      cons: 73.8,
      emission: 'N/A',
    },
    {
      model: 'GW-H430-6',
      primeKW: 315,
      primeKVA: 394,
      standbyKW: 345,
      standbyKVA: 430,
      engine: 'DP126LB',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 11.1,
      cons: 85.8,
      emission: 'N/A',
    },
    {
      model: 'GW-H500-6',
      primeKW: 350,
      primeKVA: 438,
      standbyKW: 400,
      standbyKVA: 500,
      engine: 'P158LE',
      cylinder: '8V/TCA',
      speedGovernor: 'E',
      displacement: 14.6,
      cons: 102.5,
      emission: 'N/A',
    },
    {
      model: 'GW-H563-6',
      primeKW: 410,
      primeKVA: 512,
      standbyKW: 450,
      standbyKVA: 563,
      engine: 'DP158LC',
      cylinder: '8V/TCA',
      speedGovernor: 'E',
      displacement: 14.6,
      cons: 111.5,
      emission: 'N/A',
    },
    {
      model: 'GW-H624-6',
      primeKW: 455,
      primeKVA: 569,
      standbyKW: 500,
      standbyKVA: 624,
      engine: 'DP158LD',
      cylinder: '8V/TCA',
      speedGovernor: 'E',
      displacement: 14.6,
      cons: 127.1,
      emission: 'N/A',
    },
    {
      model: 'GW-H687-6',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 550,
      standbyKVA: 687,
      engine: 'DP18OLA',
      cylinder: '10V/TCA',
      speedGovernor: 'E',
      displacement: 18.3,
      cons: 140.5,
      emission: 'N/A',
    },
    {
      model: 'GW-H750-6',
      primeKW: 544,
      primeKVA: 680,
      standbyKW: 600,
      standbyKVA: 750,
      engine: 'DP18OLB',
      cylinder: '10V/TCA',
      speedGovernor: 'E',
      displacement: 18.3,
      cons: 150.7,
      emission: 'N/A',
    },
    {
      model: 'GW-H825-6',
      primeKW: '60O',
      primeKVA: 750,
      standbyKW: '66O',
      standbyKVA: 825,
      engine: 'DP222LA',
      cylinder: '12V/TCA',
      speedGovernor: 'E',
      displacement: 21.9,
      cons: 161.7,
      emission: 'N/A',
    },
    {
      model: 'GW-H844-6',
      primeKW: 620,
      primeKVA: 775,
      standbyKW: 675,
      standbyKVA: 844,
      engine: 'DP222LB',
      cylinder: '12V/TCA',
      speedGovernor: 'E',
      displacement: 21.9,
      cons: 172.7,
      emission: 'N/A',
    },
    {
      model: 'GW-H920-6',
      primeKW: 670,
      primeKVA: 838,
      standbyKW: 736,
      standbyKVA: 920,
      engine: 'DP222LC',
      cylinder: '12V/TCA',
      speedGovernor: 'E',
      displacement: 21.9,
      cons: 183.2,
      emission: 'N/A',
    },
    {
      model: 'GW-H950-6',
      primeKW: 690,
      primeKVA: 863,
      standbyKW: 760,
      standbyKVA: 950,
      engine: 'DP222CA',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: 21.9,
      cons: 187,
      emission: 'N/A',
    },
    {
      model: 'GW-H1025-6',
      primeKW: 750,
      primeKVA: 938,
      standbyKW: 820,
      standbyKVA: 1025,
      engine: 'DP222CB',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: 21.9,
      cons: 200,
      emission: 'N/A',
    },
    {
      model: 'GW-H1100-6',
      primeKW: 800,
      primeKVA: 1000,
      standbyKW: 880,
      standbyKVA: 1100,
      engine: 'DP222CC',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: 21.9,
      cons: 223,
      emission: 'N/A',
    },
    {
      model: 'GW-H950-6',
      primeKW: 690,
      primeKVA: 863,
      standbyKW: 760,
      standbyKVA: 950,
      engine: 'DP222CA-2',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: 21.9,
      cons: 185.4,
      emission: 'T2',
    },
    {
      model: 'GW-H1025-6',
      primeKW: 750,
      primeKVA: 938,
      standbyKW: 820,
      standbyKVA: 1025,
      engine: 'DP222CB-2',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: 21.9,
      cons: 200,
      emission: 'T2',
    },
    {
      model: 'GW-H1100-6',
      primeKW: 800,
      primeKVA: 1000,
      standbyKW: 880,
      standbyKVA: 1100,
      engine: 'DP222CC-2',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: 21.9,
      cons: 223,
      emission: 'T2',
    },
  ]
})
