export default defineEventHandler(() => {
  return [
    {
      model: 'GW-IS28-6',
      primeKW: 20,
      primeKVA: 25,
      standbyKW: 22,
      standbyKVA: 28,
      engine: 'JE493DBE-03',
      cylinder: '4L/NA',
      speedGovernor: 'M',
      displacement: 2.8,
      cons: 6.9,
      emission: 'N/A',
    },
    {
      model: 'GW-IS33-6',
      primeKW: 24,
      primeKVA: 30,
      standbyKW: 26,
      standbyKVA: 33,
      engine: 'JE493DBE-01',
      cylinder: '4L/NA',
      speedGovernor: 'M',
      displacement: 2.8,
      cons: 7.7,
      emission: 'N/A',
    },
    {
      model: 'GW-IS40-6',
      primeKW: 28,
      primeKVA: 35,
      standbyKW: 32,
      standbyKVA: 40,
      engine: 'JE493ZDBE-03',
      cylinder: '4L/TC',
      speedGovernor: 'M',
      displacement: 2.8,
      cons: 6.9,
      emission: 'N/A',
    },
    {
      model: 'GW-IS44-6',
      primeKW: 32,
      primeKVA: 40,
      standbyKW: 35,
      standbyKVA: 44,
      engine: 'JE493ZLDBE-01',
      cylinder: '4L/TCA',
      speedGovernor: 'M',
      displacement: 2.8,
      cons: 9,
      emission: 'N/A',
    },
  ]
})
