export default defineEventHandler(() => {
  return [
    {
      model: 'GW-IS23',
      primeKW: 16,
      primeKVA: 20,
      standbyKW: 18,
      standbyKVA: 23,
      engine: 'JE493DB-O4',
      cylinder: '4L/NA',
      speedGovernor: 'M',
      displacement: '2.771 ',
      cons: '5.8 ',
      emission: 'N/A',
    },
    {
      model: 'GW-IS28',
      primeKW: 20,
      primeKVA: 25,
      standbyKW: 22,
      standbyKVA: 28,
      engine: 'JE493DB-O2',
      cylinder: '4L/NA',
      speedGovernor: 'M',
      displacement: '2.771 ',
      cons: '6.6 ',
      emission: 'N/A',
    },
    {
      model: 'GW-IS33',
      primeKW: 24,
      primeKVA: 30,
      standbyKW: 26,
      standbyKVA: 33,
      engine: 'JE493ZDB-04',
      cylinder: '4L/TC',
      speedGovernor: 'M',
      displacement: '2.771 ',
      cons: '7.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-IS44',
      primeKW: 32,
      primeKVA: 40,
      standbyKW: 35,
      standbyKVA: 44,
      engine: 'JE493ZLDB-O2',
      cylinder: '4L/TCA',
      speedGovernor: 'M',
      displacement: '2.771 ',
      cons: '9.6 ',
      emission: 'N/A',
    },
  ]
})
