export default defineEventHandler(() => {
  return [
    {
      model: 'GW-C35-6',
      primeKW: 25,
      primeKVA: 31,
      standbyKW: 28,
      standbyKVA: 35,
      engine: '4B3.9-G2',
      cylinder: '4L/NA',
      speedGovernor: 'E',
      displacement: 3.9,
      cons: 8.6,
      emission: 'N/A',
    },
    {
      model: 'GW-C55-6',
      primeKW: 40,
      primeKVA: 50,
      standbyKW: 44,
      standbyKVA: 55,
      engine: '4BT3.9-G2',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: 3.9,
      cons: 10.7,
      emission: 'N/A',
    },
    {
      model: 'GW-C66-6',
      primeKW: 48,
      primeKVA: 60,
      standbyKW: 53,
      standbyKVA: 66,
      engine: '4BTA3.9-G2',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: 3.9,
      cons: 15.9,
      emission: 'N/A',
    },
    {
      model: 'GW-C75-6',
      primeKW: 54,
      primeKVA: 68,
      standbyKW: 60,
      standbyKVA: 75,
      engine: '4BTA3.9-G2',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: 3.9,
      cons: 15.9,
      emission: 'N/A',
    },
    {
      model: 'GW-C100-6',
      primeKW: 72,
      primeKVA: 90,
      standbyKW: 80,
      standbyKVA: 100,
      engine: '4BTA3.9-G11',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: 3.9,
      cons: 20.1,
      emission: 'N/A',
    },
    {
      model: 'GW-C110-6',
      primeKW: 80,
      primeKVA: 100,
      standbyKW: 88,
      standbyKVA: 110,
      engine: '6BT5.9-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 5.9,
      cons: 28.5,
      emission: 'N/A',
    },
    {
      model: 'GW-C125-6',
      primeKW: 90,
      primeKVA: 113,
      standbyKW: 100,
      standbyKVA: 125,
      engine: '6BT5.9-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 5.9,
      cons: 28.5,
      emission: 'N/A',
    },
    {
      model: 'GW-C150-6',
      primeKW: 110,
      primeKVA: 138,
      standbyKW: 120,
      standbyKVA: 150,
      engine: '6BTA5.9-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 5.9,
      cons: 31,
      emission: 'N/A',
    },
    {
      model: 'GW-C165-6',
      primeKW: 120,
      primeKVA: 150,
      standbyKW: 132,
      standbyKVA: 165,
      engine: '6BTAA5.9-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 5.9,
      cons: 34,
      emission: 'N/A',
    },
    {
      model: 'GW-C188-6',
      primeKW: 136,
      primeKVA: 170,
      standbyKW: 150,
      standbyKVA: 188,
      engine: '6BTAA5.9-G12',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 5.9,
      cons: 38,
      emission: 'N/A',
    },
    {
      model: 'GW-C200-6',
      primeKW: 144,
      primeKVA: 180,
      standbyKW: 160,
      standbyKVA: 200,
      engine: '6CTA8.3-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 8.3,
      cons: 44,
      emission: 'N/A',
    },
    {
      model: 'GW-C220-6',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 176,
      standbyKVA: 220,
      engine: '6CTA8.3-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 8.3,
      cons: 44,
      emission: 'N/A',
    },
    {
      model: 'GW-C250-6',
      primeKW: 180,
      primeKVA: 225,
      standbyKW: 200,
      standbyKVA: 250,
      engine: '6CTAA8.3-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'M',
      displacement: 8.3,
      cons: 49,
      emission: 'N/A',
    },
    {
      model: 'GW-C275-6',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 220,
      standbyKVA: 275,
      engine: '6LTAA8.9-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.9,
      cons: 59,
      emission: 'N/A',
    },
    {
      model: 'GW-C300-6',
      primeKW: 220,
      primeKVA: 275,
      standbyKW: 240,
      standbyKVA: 300,
      engine: '6LTAA8.9-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 8.9,
      cons: 59,
      emission: 'N/A',
    },
    {
      model: 'GW-C350-6',
      primeKW: 250,
      primeKVA: 313,
      standbyKW: 280,
      standbyKVA: 350,
      engine: 'NTA855-G1',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: 14,
      cons: 73.4,
      emission: 'N/A',
    },
    {
      model: 'GW-C344-6',
      primeKW: 250,
      primeKVA: 313,
      standbyKW: 275,
      standbyKVA: 344,
      engine: '6LTAA9.5-G1',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 9.5,
      cons: 68,
      emission: 'N/A',
    },
    {
      model: 'GW-C388-6',
      primeKW: 280,
      primeKVA: 350,
      standbyKW: 310,
      standbyKVA: 388,
      engine: 'NTA855-G1B',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 14,
      cons: 80.5,
      emission: 'N/A',
    },
    {
      model: 'GW-C413-6',
      primeKW: 300,
      primeKVA: 375,
      standbyKW: 330,
      standbyKVA: 413,
      engine: 'QSM11-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 9.5,
      cons: 78.6,
      emission: 'N/A',
    },
    {
      model: 'GW-C440-6',
      primeKW: 320,
      primeKVA: 400,
      standbyKW: 350,
      standbyKVA: 440,
      engine: 'QSM11-G4',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 13,
      cons: 83.6,
      emission: 'N/A',
    },
    {
      model: 'GW-C440-6',
      primeKW: 320,
      primeKVA: 400,
      standbyKW: 350,
      standbyKVA: 440,
      engine: 'NTA855-G3',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 14,
      cons: 87.1,
      emission: 'N/A',
    },
    {
      model: 'GW-C500-6',
      primeKW: 360,
      primeKVA: 450,
      standbyKW: 400,
      standbyKVA: 500,
      engine: 'KTA19-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 19,
      cons: 91.4,
      emission: 'N/A',
    },
    {
      model: 'GW-C523-6',
      primeKW: 380,
      primeKVA: 475,
      standbyKW: 418,
      standbyKVA: 523,
      engine: 'QSZ13-G5',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 13,
      cons: 102.1,
      emission: 'N/A',
    },
    {
      model: 'GW-C550-6',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: 'KTA19-G3',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 19,
      cons: 110.6,
      emission: 'N/A',
    },
    {
      model: 'GW-C600-6',
      primeKW: 440,
      primeKVA: 550,
      standbyKW: 485,
      standbyKVA: 600,
      engine: 'QSZ13-G11',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 13,
      cons: 121,
      emission: 'N/A',
    },
    {
      model: 'GW-C625-6',
      primeKW: 450,
      primeKVA: 563,
      standbyKW: 500,
      standbyKVA: 625,
      engine: 'KTA19-G3A',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 13,
      cons: 120,
      emission: 'N/A',
    },
    {
      model: 'GW-C688-6',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 550,
      standbyKVA: 688,
      engine: 'KTAA19-G5',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 13,
      cons: 130.6,
      emission: 'N/A',
    },
    {
      model: 'GW-C750-6',
      primeKW: 545,
      primeKVA: 681,
      standbyKW: 600,
      standbyKVA: 750,
      engine: 'KTAA19-G6A',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 13,
      cons: 167,
      emission: 'N/A',
    },
    {
      model: 'GW-C850-6',
      primeKW: 620,
      primeKVA: 775,
      standbyKW: 680,
      standbyKVA: 850,
      engine: 'KT38-G',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: 38,
      cons: 154,
      emission: 'N/A',
    },
    {
      model: 'GW-C963-6',
      primeKW: 700,
      primeKVA: 875,
      standbyKW: 770,
      standbyKVA: 963,
      engine: 'KTA38-G1',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: 38,
      cons: 195.3,
      emission: 'N/A',
    },
    {
      model: 'GW-C1000-6',
      primeKW: 728,
      primeKVA: 910,
      standbyKW: 800,
      standbyKVA: 1000,
      engine: 'KTA38-G2',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: 38,
      cons: 203.5,
      emission: 'N/A',
    },
    {
      model: 'GW-C1038-6',
      primeKW: 748,
      primeKVA: 935,
      standbyKW: 830,
      standbyKVA: 1038,
      engine: 'KTA38-G2B',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: 38,
      cons: 204,
      emission: 'N/A',
    },
    {
      model: 'GW-C1125-6',
      primeKW: 820,
      primeKVA: 1025,
      standbyKW: 900,
      standbyKVA: 1125,
      engine: 'KTA38-G2A',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: 38,
      cons: 221,
      emission: 'N/A',
    },
    {
      model: 'GW-C1250-6',
      primeKW: 910,
      primeKVA: 1138,
      standbyKW: 1000,
      standbyKVA: 1250,
      engine: 'KTA38-G4',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: 38,
      cons: 244.7,
      emission: 'N/A',
    },
    {
      model: 'GW-C1375-6',
      primeKW: 1000,
      primeKVA: 1250,
      standbyKW: 1100,
      standbyKVA: 1375,
      engine: 'KTA38-G9',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: 38,
      cons: 367,
      emission: 'N/A',
    },
    {
      model: 'GW-C1563-6',
      primeKW: 1134,
      primeKVA: 1418,
      standbyKW: 1250,
      standbyKVA: 1563,
      engine: 'KTA50-G3',
      cylinder: '16V/TW',
      speedGovernor: 'E',
      displacement: 50,
      cons: 291,
      emission: 'T2',
    },
    {
      model: 'GW-C1875-6',
      primeKW: 1295,
      primeKVA: 1619,
      standbyKW: 1500,
      standbyKVA: 1875,
      engine: 'KTA50-G9',
      cylinder: '16V/TW',
      speedGovernor: 'E',
      displacement: 50,
      cons: 330,
      emission: 'T2',
    },
  ]
})
