export default defineEventHandler(() => {
  return [
    {
      model: 'GW-H69',
      primeKW: 50,
      primeKVA: 63,
      standbyKW: 55,
      standbyKVA: 69,
      engine: 'SP344CB',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '3.409',
      cons: '10.5',
      emission: 'N/A',
    },
    {
      model: 'GW-H88',
      primeKW: 64,
      primeKVA: 80,
      standbyKW: 70,
      standbyKVA: 88,
      engine: 'SP344CC',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '3.409',
      cons: '13.6',
      emission: 'N/A',
    },
    {
      model: 'GW-H139',
      primeKW: 101,
      primeKVA: 126,
      standbyKW: 111,
      standbyKVA: 139,
      engine: 'DP054CA',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '5.000',
      cons: '21.5',
      emission: 'N/A',
    },
    {
      model: 'GW-H175',
      primeKW: 127,
      primeKVA: 159,
      standbyKW: 140,
      standbyKVA: 175,
      engine: 'DP054CB',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '5.000',
      cons: '26.8',
      emission: 'N/A',
    },
    {
      model: 'GW-H213',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 170,
      standbyKVA: 213,
      engine: 'DP054CC',
      cylinder: '4L/TCA',
      speedGovernor: 'ECU',
      displacement: '5.000',
      cons: '32.3',
      emission: 'N/A',
    },
    {
      model: 'GW-H239',
      primeKW: 173,
      primeKVA: 216,
      standbyKW: 191,
      standbyKVA: 239,
      engine: 'DP086CA',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.500',
      cons: '36.1',
      emission: 'N/A',
    },
    {
      model: 'GW-H256',
      primeKW: 186,
      primeKVA: 233,
      standbyKW: 205,
      standbyKVA: 256,
      engine: 'DP086CB',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.500',
      cons: '39.5',
      emission: 'N/A',
    },
    {
      model: 'GW-H280',
      primeKW: 203,
      primeKVA: 254,
      standbyKW: 224,
      standbyKVA: 280,
      engine: 'DP086CC',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.500',
      cons: '42.8',
      emission: 'N/A',
    },
    {
      model: 'GW-H309',
      primeKW: 224,
      primeKVA: 280,
      standbyKW: 247,
      standbyKVA: 309,
      engine: 'DP086CD',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.500',
      cons: '47.3',
      emission: 'N/A',
    },
    {
      model: 'GW-H336',
      primeKW: 244,
      primeKVA: 305,
      standbyKW: 269,
      standbyKVA: 336,
      engine: 'DP086CE',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '7.500',
      cons: '51.5',
      emission: 'N/A',
    },
    {
      model: 'GW-H185',
      primeKW: 134,
      primeKVA: 168,
      standbyKW: 148,
      standbyKVA: 185,
      engine: 'P086TI-1',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '8.071',
      cons: '36.0',
      emission: 'N/A',
    },
    {
      model: 'GW-H225',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 180,
      standbyKVA: 225,
      engine: 'P086TI',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '8.071',
      cons: '43.0',
      emission: 'T2',
    },
    {
      model: 'GW-H254',
      primeKW: 183,
      primeKVA: 229,
      standbyKW: 203,
      standbyKVA: 254,
      engine: 'DP086LA',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '8.071',
      cons: '49.3',
      emission: 'N/A',
    },
    {
      model: 'GW-H308',
      primeKW: 218,
      primeKVA: 273,
      standbyKW: 246,
      standbyKVA: 308,
      engine: 'P126TI',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '11.051',
      cons: '58.6',
      emission: 'T2',
    },
    {
      model: 'GW-H334',
      primeKW: 240,
      primeKVA: 300,
      standbyKW: 267,
      standbyKVA: 334,
      engine: 'P126TI-II',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '11.051',
      cons: '62.7',
      emission: 'N/A',
    },
    {
      model: 'GW-H406',
      primeKW: 292,
      primeKVA: 365,
      standbyKW: 325,
      standbyKVA: 406,
      engine: 'DP126LB',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '11.051',
      cons: '76.0',
      emission: 'N/A',
    },
    {
      model: 'GW-H344',
      primeKW: 250,
      primeKVA: 313,
      standbyKW: 275,
      standbyKVA: 344,
      engine: 'DP126CA',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '11.051',
      cons: '69.0',
      emission: 'N/A',
    },
    {
      model: 'GW-H390',
      primeKW: 282,
      primeKVA: 353,
      standbyKW: 312,
      standbyKVA: 390,
      engine: 'DP126CB',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '11.051',
      cons: '78.0',
      emission: 'N/A',
    },
    {
      model: 'GW-H450',
      primeKW: 325,
      primeKVA: 406,
      standbyKW: 360,
      standbyKVA: 450,
      engine: 'DP126CD',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '11.051',
      cons: '89.0',
      emission: 'N/A',
    },
    {
      model: 'GW-H479',
      primeKW: 347,
      primeKVA: 434,
      standbyKW: 383,
      standbyKVA: 479,
      engine: 'DP126CE',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '11.051',
      cons: '95.0',
      emission: 'N/A',
    },
    {
      model: 'GW-H468',
      primeKW: 326,
      primeKVA: 408,
      standbyKW: 374,
      standbyKVA: 468,
      engine: 'P158LE',
      cylinder: '8V/TCA',
      speedGovernor: 'E',
      displacement: '14.618',
      cons: '86.6',
      emission: 'N/A',
    },
    {
      model: 'GW-H511',
      primeKW: 370,
      primeKVA: 463,
      standbyKW: 409,
      standbyKVA: 511,
      engine: 'DP158LC',
      cylinder: '8V/TCA',
      speedGovernor: 'E',
      displacement: '14.618',
      cons: '97.3',
      emission: 'N/A',
    },
    {
      model: 'GW-H583',
      primeKW: 423,
      primeKVA: 529,
      standbyKW: 466,
      standbyKVA: 583,
      engine: 'DP158LD',
      cylinder: '8V/TCA',
      speedGovernor: 'E',
      displacement: '14.618',
      cons: '110.7',
      emission: 'N/A',
    },
    {
      model: 'GW-H633',
      primeKW: 459,
      primeKVA: 574,
      standbyKW: 506,
      standbyKVA: 633,
      engine: 'DP180LA',
      cylinder: '10V/TCA',
      speedGovernor: 'E',
      displacement: '18.273',
      cons: '125.3',
      emission: 'N/A',
    },
    {
      model: 'GW-H703',
      primeKW: 509,
      primeKVA: 636,
      standbyKW: 562,
      standbyKVA: 703,
      engine: 'DP180LB',
      cylinder: '10V/TCA',
      speedGovernor: 'E',
      displacement: '18.273',
      cons: '138.7',
      emission: 'N/A',
    },
    {
      model: 'GW-H759',
      primeKW: 551,
      primeKVA: 689,
      standbyKW: 607,
      standbyKVA: 759,
      engine: 'DP222LB',
      cylinder: '12V/TCA',
      speedGovernor: 'E',
      displacement: '21.927',
      cons: '145.3',
      emission: 'N/A',
    },
    {
      model: 'GW-H829',
      primeKW: 601,
      primeKVA: 751,
      standbyKW: 663,
      standbyKVA: 829,
      engine: 'DP222LC',
      cylinder: '12V/TCA',
      speedGovernor: 'E',
      displacement: '21.927',
      cons: '158.7',
      emission: 'N/A',
    },
    {
      model: 'GW-H839',
      primeKW: 610,
      primeKVA: 763,
      standbyKW: 671,
      standbyKVA: 839,
      engine: 'DP222CA',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: '21.927',
      cons: '177.0',
      emission: 'N/A',
    },
    {
      model: 'GW-H900',
      primeKW: 650,
      primeKVA: 813,
      standbyKW: 720,
      standbyKVA: 900,
      engine: 'DP222CB',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: '21.927',
      cons: '193.3',
      emission: 'N/A',
    },
    {
      model: 'GW-H1000',
      primeKW: 730,
      primeKVA: 913,
      standbyKW: 800,
      standbyKVA: 1000,
      engine: 'DP222CC',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: '21.927',
      cons: '196.0',
      emission: 'N/A',
    },
  ]
})
