export default defineEventHandler(() => {
  return [
    {
      model: 'GW-C28',
      primeKW: 20,
      primeKVA: 25,
      standbyKW: 22,
      standbyKVA: 28,
      engine: '4B3.9-G1',
      cylinder: '4L/NA',
      speedGovernor: 'M',
      displacement: '3.9 ',
      cons: '6.5 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C30',
      primeKW: 22,
      primeKVA: 28,
      standbyKW: 24,
      standbyKVA: 30,
      engine: '483.9G2',
      cylinder: '4L/NA',
      speedGovernor: 'E',
      displacement: '3.9 ',
      cons: '6.7 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C44',
      primeKW: 32,
      primeKVA: 40,
      standbyKW: 35,
      standbyKVA: 44,
      engine: '4BT3.9G1',
      cylinder: '4L/TC',
      speedGovernor: 'M',
      displacement: '3.9 ',
      cons: '10.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C44',
      primeKW: 32,
      primeKVA: 40,
      standbyKW: 35,
      standbyKVA: 44,
      engine: '4BT3.9-G2',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: '3.9 ',
      cons: '9.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C62',
      primeKW: 45,
      primeKVA: 56,
      standbyKW: 50,
      standbyKVA: 62,
      engine: '4BTA3.9-G2',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: '3.9 ',
      cons: '12.9 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C70',
      primeKW: 52,
      primeKVA: 65,
      standbyKW: 56,
      standbyKVA: 70,
      engine: '4BTA3.9-G2',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: '3.9 ',
      cons: '14.9 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C85',
      primeKW: 64,
      primeKVA: 80,
      standbyKW: 68,
      standbyKVA: 85,
      engine: '4BTA3.9-G11',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: '3.9 ',
      cons: '17.6 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C110',
      primeKW: 80,
      primeKVA: 100,
      standbyKW: 88,
      standbyKVA: 110,
      engine: '4BTA3.9-G13',
      cylinder: '4L/TW',
      speedGovernor: 'E',
      displacement: '3.9 ',
      cons: '20.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C110',
      primeKW: 80,
      primeKVA: 100,
      standbyKW: 88,
      standbyKVA: 110,
      engine: '6BT5.9-G2',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '5.9 ',
      cons: '23.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C125',
      primeKW: 92,
      primeKVA: 115,
      standbyKW: 100,
      standbyKVA: 125,
      engine: '6BTA5.9-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: '5.9 ',
      cons: '27.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C145',
      primeKW: 108,
      primeKVA: 135,
      standbyKW: 116,
      standbyKVA: 145,
      engine: '6BTAA5.9-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '5.9 ',
      cons: '30.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C165',
      primeKW: 120,
      primeKVA: 150,
      standbyKW: 132,
      standbyKVA: 165,
      engine: '6BTAA5.9G12',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '5.9 ',
      cons: '34.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C200',
      primeKW: 145,
      primeKVA: 180,
      standbyKW: 160,
      standbyKVA: 200,
      engine: '6CTA8.3-G1',
      cylinder: '6L/TW',
      speedGovernor: 'M',
      displacement: '8.3 ',
      cons: '42.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C200',
      primeKW: 145,
      primeKVA: 180,
      standbyKW: 160,
      standbyKVA: 200,
      engine: '6CTA8.3-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: '8.3 ',
      cons: '42.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C215',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 172,
      standbyKVA: 215,
      engine: '6CTAA8.3-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '8.3 ',
      cons: '45.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C262',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 210,
      standbyKVA: 262,
      engine: '6LTAA8.9-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '8.9 ',
      cons: '53.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C275',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 220,
      standbyKVA: 275,
      engine: '6LTAA8.9-G3',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '8.9 ',
      cons: '54.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C313',
      primeKW: 220,
      primeKVA: 275,
      standbyKW: 250,
      standbyKVA: 313,
      engine: '6LTAA9.5-G3',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '9.5 ',
      cons: '58.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C350',
      primeKW: 250,
      primeKVA: 313,
      standbyKW: 280,
      standbyKVA: 350,
      engine: '6LTAA9.5G1',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '9.5 ',
      cons: '70.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C425',
      primeKW: 310,
      primeKVA: 388,
      standbyKW: 340,
      standbyKVA: 425,
      engine: '6ZTAA13-G3',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 13,
      cons: '74.7 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C475',
      primeKW: 340,
      primeKVA: 425,
      standbyKW: 380,
      standbyKVA: 475,
      engine: '6ZTAA13-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 13,
      cons: '85.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C475',
      primeKW: 350,
      primeKVA: 438,
      standbyKW: 380,
      standbyKVA: 475,
      engine: '6ZTAA13-G4',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 13,
      cons: '91.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C475',
      primeKW: 350,
      primeKVA: 438,
      standbyKW: 380,
      standbyKVA: 475,
      engine: 'QSZ13-G2',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 13,
      cons: '88.8 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C500',
      primeKW: 360,
      primeKVA: 450,
      standbyKW: 400,
      standbyKVA: 500,
      engine: 'QSZ13-G5',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 13,
      cons: '93.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C500',
      primeKW: 380,
      primeKVA: 475,
      standbyKW: 400,
      standbyKVA: 500,
      engine: 'QSZ13-G3',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 13,
      cons: '101.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C550',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: 'QSZ13-G10',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 13,
      cons: '107.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C275',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 220,
      standbyKVA: 275,
      engine: 'NT855-GA',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: 14,
      cons: '53.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C313',
      primeKW: 220,
      primeKVA: 275,
      standbyKW: 250,
      standbyKVA: 313,
      engine: 'NTA855-G1A',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 14,
      cons: '61.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C350',
      primeKW: 250,
      primeKVA: 313,
      standbyKW: 280,
      standbyKVA: 350,
      engine: 'NTA855G1B',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 14,
      cons: '68.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C375',
      primeKW: 275,
      primeKVA: 345,
      standbyKW: 300,
      standbyKVA: 375,
      engine: 'NTA855-G2A',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 14,
      cons: '73.9 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C390',
      primeKW: 280,
      primeKVA: 350,
      standbyKW: 310,
      standbyKVA: 390,
      engine: 'NTA855-G4',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 14,
      cons: '76.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C400',
      primeKW: 300,
      primeKVA: 375,
      standbyKW: 320,
      standbyKVA: 400,
      engine: 'NTAA855-G7',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 14,
      cons: '85.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C438',
      primeKW: 320,
      primeKVA: 400,
      standbyKW: 350,
      standbyKVA: 438,
      engine: 'QSNT-G3',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: 14,
      cons: '88.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C450',
      primeKW: 330,
      primeKVA: 413,
      standbyKW: 360,
      standbyKVA: 450,
      engine: 'NTAA855-G7A',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: 14,
      cons: '89.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C412',
      primeKW: 300,
      primeKVA: 375,
      standbyKW: 330,
      standbyKVA: 412,
      engine: 'KTA19-G2',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 19,
      cons: '86.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C500',
      primeKW: 360,
      primeKVA: 450,
      standbyKW: 400,
      standbyKVA: 500,
      engine: 'KTA19-G3',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 19,
      cons: '97.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C550',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: 'KTA19-G3A',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: 19,
      cons: '107.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C550',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: 'KTA19-G4',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: '107.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C600',
      primeKW: 420,
      primeKVA: 525,
      standbyKW: 480,
      standbyKVA: 600,
      engine: 'KTAA19G5',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: '113.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C650',
      primeKW: 470,
      primeKVA: 588,
      standbyKW: 520,
      standbyKVA: 650,
      engine: 'KTA19-G8',
      cylinder: '6L/TW',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: '128.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C650',
      primeKW: 460,
      primeKVA: 575,
      standbyKW: 520,
      standbyKVA: 650,
      engine: 'KTAA19G6',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: '128.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C650',
      primeKW: 480,
      primeKVA: 600,
      standbyKW: 520,
      standbyKVA: 650,
      engine: 'KTAA19-G6A',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: '129.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C687',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 550,
      standbyKVA: 687,
      engine: 'KTAA19-G6A',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: '135.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C687',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 550,
      standbyKVA: 687,
      engine: 'KTAA19G7',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: '135.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C700',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 560,
      standbyKVA: 700,
      engine: 'KT38-G',
      cylinder: '12V/TC',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '145.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C787',
      primeKW: 570,
      primeKVA: 712,
      standbyKW: 630,
      standbyKVA: 787,
      engine: 'KTA38-G1',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '155.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C800',
      primeKW: 580,
      primeKVA: 725,
      standbyKW: 640,
      standbyKVA: 800,
      engine: 'KT38-GA',
      cylinder: '12V/TC',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '16O.0',
      emission: 'N/A',
    },
    {
      model: 'GW-C825',
      primeKW: 600,
      primeKVA: 750,
      standbyKW: 660,
      standbyKVA: 825,
      engine: 'KTA38-G2',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '167.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C880',
      primeKW: 640,
      primeKVA: 800,
      standbyKW: 704,
      standbyKVA: 880,
      engine: 'KTA38-G2B',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '170.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1000',
      primeKW: 728,
      primeKVA: 910,
      standbyKW: 800,
      standbyKVA: 1000,
      engine: 'KTA38-G2A',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '190.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1100',
      primeKW: 800,
      primeKVA: 1000,
      standbyKW: 880,
      standbyKVA: 1100,
      engine: 'KTA38-G5',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '209.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1250',
      primeKW: 900,
      primeKVA: 1125,
      standbyKW: 1000,
      standbyKVA: 1250,
      engine: 'KTA38-G9',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '256.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1375',
      primeKW: 1000,
      primeKVA: 1250,
      standbyKW: 1100,
      standbyKVA: 1375,
      engine: 'KTA50-G3',
      cylinder: '16V/TW',
      speedGovernor: 'E',
      displacement: '50.0 ',
      cons: '274.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1600',
      primeKW: 1100,
      primeKVA: 1375,
      standbyKW: 1280,
      standbyKVA: 1600,
      engine: 'KTA5O-G8',
      cylinder: '16V/TW',
      speedGovernor: 'E',
      displacement: '50.0 ',
      cons: '289.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1600',
      primeKW: 1180,
      primeKVA: 1475,
      standbyKW: 1280,
      standbyKVA: 1600,
      engine: 'KTA50-GS8',
      cylinder: '16V/TW',
      speedGovernor: 'E',
      displacement: '50.0 ',
      cons: '309.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C550',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 440,
      standbyKVA: 550,
      engine: 'QSX15-G8',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '15.0 ',
      cons: '103.0 ',
      emission: 'T2/EU Ⅱ',
    },
    {
      model: 'GW-C700',
      primeKW: 516,
      primeKVA: 645,
      standbyKW: 560,
      standbyKVA: 700,
      engine: 'VTA28-G5',
      cylinder: '12V/TW',
      speedGovernor: 'E',
      displacement: '28.0 ',
      cons: '145.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C880',
      primeKW: 640,
      primeKVA: 800,
      standbyKW: 704,
      standbyKVA: 880,
      engine: 'QSK23-G3',
      cylinder: '6L/TCA',
      speedGovernor: 'ECU',
      displacement: '23.0 ',
      cons: '161.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1100',
      primeKW: 800,
      primeKVA: 1000,
      standbyKW: 880,
      standbyKVA: 1100,
      engine: 'QST3O-G4',
      cylinder: '12V/TCA',
      speedGovernor: 'ECU',
      displacement: '30.5 ',
      cons: '202.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1540',
      primeKW: 1120,
      primeKVA: 1400,
      standbyKW: 1232,
      standbyKVA: 1540,
      engine: 'QSK50-G3',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '50.3 ',
      cons: '313.0 ',
      emission: 'T2',
    },
    {
      model: 'GW-C1700',
      primeKW: 1232,
      primeKVA: 1540,
      standbyKW: 1360,
      standbyKVA: 1700,
      engine: 'QSK50-G4',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '50.3 ',
      cons: '338.D',
      emission: 'T2',
    },
    {
      model: 'GW-C1825',
      primeKW: 1320,
      primeKVA: 1650,
      standbyKW: 1460,
      standbyKVA: 1825,
      engine: 'QSK50-G7',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '50.3 ',
      cons: '349.0 ',
      emission: 'T2',
    },
    {
      model: 'GW-C1875',
      primeKW: 1370,
      primeKVA: 1713,
      standbyKW: 1500,
      standbyKVA: 1875,
      engine: 'QSK50G13',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '50.3 ',
      cons: '357.0 ',
      emission: 'T2',
    },
    {
      model: 'GW-C2000',
      primeKW: 1500,
      primeKVA: 1875,
      standbyKW: 1600,
      standbyKVA: 2000,
      engine: 'QSK50-G16',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '50.3 ',
      cons: '376.0 ',
      emission: 'T2',
    },
    {
      model: 'GW-C2000',
      primeKW: 1500,
      primeKVA: 1875,
      standbyKW: 1600,
      standbyKVA: 2000,
      engine: 'QSKGO-G3',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '60.2 ',
      cons: '371.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C2200',
      primeKW: 1600,
      primeKVA: 2000,
      standbyKW: 1760,
      standbyKVA: 2200,
      engine: 'QSK50-G17',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '50.3 ',
      cons: '399.0 ',
      emission: 'T2',
    },
    {
      model: 'GW-C2200',
      primeKW: 1600,
      primeKVA: 2000,
      standbyKW: 1760,
      standbyKVA: 2200,
      engine: 'QSK6O-G4',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '60.2 ',
      cons: '394.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C2500',
      primeKW: 1800,
      primeKVA: 2250,
      standbyKW: 2000,
      standbyKVA: 2500,
      engine: 'QSKGO-G8',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '60.2 ',
      cons: '446.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C2500',
      primeKW: 1800,
      primeKVA: 2250,
      standbyKW: 2000,
      standbyKVA: 2500,
      engine: 'QSK6O-G21',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '60.2 ',
      cons: '455.0 ',
      emission: 'T2',
    },
    {
      model: 'GW-C2750',
      primeKW: 2000,
      primeKVA: 2500,
      standbyKW: 2200,
      standbyKVA: 2750,
      engine: 'QSK6O-G23',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '60.2 ',
      cons: '496.5 ',
      emission: 'T2',
    },
    {
      model: 'GW-C2750',
      primeKW: 2000,
      primeKVA: 2500,
      standbyKW: 2200,
      standbyKVA: 2750,
      engine: 'QSK78-G18',
      cylinder: '18V/TW',
      speedGovernor: 'ECU',
      displacement: '77.6 ',
      cons: '481.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C3000',
      primeKW: 2200,
      primeKVA: 2750,
      standbyKW: 2400,
      standbyKVA: 3000,
      engine: 'QSK78-G9',
      cylinder: '18V/TW',
      speedGovernor: 'ECU',
      displacement: '77.6 ',
      cons: '528.0 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C3763',
      primeKW: 2690,
      primeKVA: 3363,
      standbyKW: 3010,
      standbyKVA: 3763,
      engine: 'QSK95-G4',
      cylinder: '16V/TW',
      speedGovernor: 'ECU',
      displacement: '95.3 ',
      cons: '645.0 ',
      emission: 'N/A',
    },
  ]
})
