export default defineEventHandler(() => {
  return [
    {
      model: 'GW-W75NG',
      primeKW: 60,
      primeKVA: 75,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'WP4D77E301NG',
      cylinder: '4L/TCA',
      speedGovernor: 'E',
      displacement: '4.50 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-W125NG',
      primeKW: 100,
      primeKVA: 125,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'WP6D132E300NG',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '6.750 ',
      cons: '0.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-W150NG',
      primeKW: 120,
      primeKVA: 150,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'WP10D200E301NG',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '9.726 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-W250NG',
      primeKW: 200,
      primeKVA: 250,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'WP13D317E301NG',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '12.540 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
  ]
})
