export default defineEventHandler(() => {
  return [
    {
      model: 'GW-Y63NG',
      primeKW: 50,
      primeKVA: 62.5,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC4D90N-D30',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: '4.21 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y75NG',
      primeKW: 60,
      primeKVA: 75,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC4G115N-D30',
      cylinder: '4L/TC',
      speedGovernor: 'E',
      displacement: '4.76 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y100NG',
      primeKW: 80,
      primeKVA: 100,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6G155N-D30',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '14.81 ',
      cons: '0.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y125NG',
      primeKW: 100,
      primeKVA: 125,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6G180N-D30',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '12.90 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y200NG',
      primeKW: 160,
      primeKVA: 200,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6MK270N-D30',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '10.34 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y225NG',
      primeKW: 180,
      primeKVA: 225,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6MK315N-D30',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '10.34 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y313NG',
      primeKW: 250,
      primeKVA: 312.5,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6K420N-D30',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '12.94 ',
      cons: '0.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y313NG',
      primeKW: 250,
      primeKVA: 312.5,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6T450N-D30',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '16.4 ',
      cons: '0.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y438NG',
      primeKW: 350,
      primeKVA: 437.5,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6TD600N-D32',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '19.6 ',
      cons: '0.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y438NG',
      primeKW: 350,
      primeKVA: 437.5,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6TD600N-D31',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '19.6 ',
      cons: '0.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y625NG',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6C935N-D30',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '39.6 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-Y750NG',
      primeKW: 600,
      primeKVA: 750,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'YC6C1020N-D30',
      cylinder: '6L/TC',
      speedGovernor: 'E',
      displacement: '39.58 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
  ]
})
