export default defineEventHandler(() => {
  return [
    {
      model: 'GW-B500NG',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: '6M33D450E310NG',
      cylinder: '6L/TCA',
      speedGovernor: 'E',
      displacement: '19.600 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-B625NG',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: '12M26D605E300NG',
      cylinder: '12V/TCA',
      speedGovernor: 'E',
      displacement: '31.80 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-B1000NG',
      primeKW: 800,
      primeKVA: 1000,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: '12M33D900E310NG',
      cylinder: '12V/TCW',
      speedGovernor: 'E',
      displacement: '39.60 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-B1250NG',
      primeKW: 1000,
      primeKVA: 1250,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: '16M33D1150A0BG',
      cylinder: '16V/TCW',
      speedGovernor: 'E',
      displacement: '52.30 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-B1500NG',
      primeKW: 1200,
      primeKVA: 1500,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: '16M33D1280NG10',
      cylinder: '16V/TCW',
      speedGovernor: 'E',
      displacement: '52.30 ',
      cons: '0.2 ',
      emission: 'N/A',
    },
    {
      model: 'GW-B1875NG',
      primeKW: 1500,
      primeKVA: 1875,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: '12M55D1588A0NG',
      cylinder: '12V/TCW',
      speedGovernor: 'E',
      displacement: '65.65 ',
      cons: '0.5 ',
      emission: 'N/A',
    },
  ]
})
