export default defineEventHandler(() => {
  return [
    {
      model: 'GW-C375NG',
      primeKW: 300,
      primeKVA: 375,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K19N-G1',
      cylinder: '6L/TCW',
      speedGovernor: 'E',
      displacement: '19.00 ',
      cons: '0.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C438NG',
      primeKW: 350,
      primeKVA: 437.5,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K19N-G3',
      cylinder: '6L/TCW',
      speedGovernor: 'E',
      displacement: '19.00 ',
      cons: '0.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C500NG',
      primeKW: 400,
      primeKVA: 500,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K19N-G4',
      cylinder: '6L/TCW',
      speedGovernor: 'E',
      displacement: '19.00 ',
      cons: '0.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C625NG',
      primeKW: 500,
      primeKVA: 625,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K38N-G5',
      cylinder: '12V/TCW',
      speedGovernor: 'E',
      displacement: '38.00 ',
      cons: '0.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C750NG',
      primeKW: 600,
      primeKVA: 750,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K38N-G6',
      cylinder: '12V/TCW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '0.3 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C875NG',
      primeKW: 700,
      primeKVA: 875,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K38N-G7',
      cylinder: '12V/TCW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '0.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1000NG',
      primeKW: 800,
      primeKVA: 1000,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K38N-G8',
      cylinder: '12V/TCW',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: '0.4 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1125NG',
      primeKW: 900,
      primeKVA: 1125,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K50N-G9',
      cylinder: '16V/TCW',
      speedGovernor: 'E',
      displacement: '50.30 ',
      cons: '0.5 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1250NG',
      primeKW: 1000,
      primeKVA: 1250,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K50N-G10',
      cylinder: '16V/TCW',
      speedGovernor: 'E',
      displacement: '50.30 ',
      cons: '0.5 ',
      emission: 'N/A',
    },
    {
      model: 'GW-C1250NG',
      primeKW: 1000,
      primeKVA: 1250,
      standbyKW: 'N/A',
      standbyKVA: 'N/A',
      engine: 'K50N-G11S',
      cylinder: '16V/TCW',
      speedGovernor: 'E',
      displacement: '50.30 ',
      cons: '0.5 ',
      emission: 'N/A',
    },
  ]
})
