export default defineEventHandler(() => {
  return [
    {
      model: 'GW-Z200M',
      primeKW: 200,
      primeKVA: 250,
      engine: 'EZ6170ZLD-2',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 27.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z250M',
      primeKW: 250,
      primeKVA: 313,
      engine: 'EZ6170ZLD-1',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 27.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z300M',
      primeKW: 300,
      primeKVA: 375,
      engine: 'EZ6170ZLD',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 27.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z350M',
      primeKW: 350,
      primeKVA: 438,
      engine: 'EZ6170ZLD-10',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 27.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z400M',
      primeKW: 400,
      primeKVA: 500,
      engine: 'EZ8170ZLD',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 36.3,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z450M',
      primeKW: 450,
      primeKVA: 563,
      engine: 'EZ8170ZLCZ-7',
      cylinder: '8L',
      speedGovernor: 'E',
      displacement: 36.3,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z500M',
      primeKW: 500,
      primeKVA: 625,
      engine: 'EZ8170ZLCZ-6',
      cylinder: '8L',
      speedGovernor: 'E',
      displacement: 36.3,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z550M',
      primeKW: 550,
      primeKVA: 688,
      engine: 'EZ8180ZLD-4',
      cylinder: '8L',
      speedGovernor: 'E',
      displacement: 36.3,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z600M',
      primeKW: 600,
      primeKVA: 750,
      engine: 'EZ8180ZLD-2A',
      cylinder: '8L',
      speedGovernor: 'E',
      displacement: 36.3,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-Z700M',
      primeKW: 700,
      primeKVA: 875,
      engine: 'EZ8180ZLD-1',
      cylinder: '8L',
      speedGovernor: 'E',
      displacement: 36.3,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
  ]
})
