export default defineEventHandler(() => {
  return [
    {
      model: 'GW-C50M',
      primeKW: 40,
      primeKVA: 50,
      engine: '4BTA3.9-G(M)47',
      cylinder: '4L',
      speedGovernor: 'E',
      displacement: '4.5 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C63M',
      primeKW: 50,
      primeKVA: 63,
      engine: '6BT5.9-G(M)83',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '5.9 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C88M',
      primeKW: 70,
      primeKVA: 88,
      engine: '6BT5.9-G(M)83',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '5.9 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C113M',
      primeKW: 90,
      primeKVA: 113,
      engine: '6BTA5.9-G(M)100',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '5.9 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C125M',
      primeKW: 100,
      primeKVA: 125,
      engine: '6CT8.3-G(M)115',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '8.3 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C150M',
      primeKW: 120,
      primeKVA: 150,
      engine: '6CT8.3-G(M)155',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '8.3 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C175M',
      primeKW: 140,
      primeKVA: 175,
      engine: '6CT8.3-G(M)155',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '8.3 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C200M',
      primeKW: 160,
      primeKVA: 200,
      engine: '6LTAA8.9-G(M)200',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '8.9 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C225M',
      primeKW: 180,
      primeKVA: 225,
      engine: 'NT855-D(M)',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '14.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C250M',
      primeKW: 200,
      primeKVA: 250,
      engine: 'NT855-D(M)',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '14.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C313M',
      primeKW: 250,
      primeKVA: 313,
      engine: 'NT855-D(M)',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '14.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C350M',
      primeKW: 280,
      primeKVA: 350,
      engine: 'NT855-D(M)',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '14.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C400M',
      primeKW: 320,
      primeKVA: 400,
      engine: 'K19-D(M)',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C450M',
      primeKW: 360,
      primeKVA: 450,
      engine: 'K19-D(M)',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C500M',
      primeKW: 400,
      primeKVA: 500,
      engine: 'K19-D(M)',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: '19.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C625M',
      primeKW: 500,
      primeKVA: 625,
      engine: 'K38-D(M)',
      cylinder: '12V',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C700M',
      primeKW: 560,
      primeKVA: 700,
      engine: 'K38-D(M)',
      cylinder: '12V',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C825M',
      primeKW: 660,
      primeKVA: 825,
      engine: 'K38-D(M)',
      cylinder: '12V',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C875M',
      primeKW: 700,
      primeKVA: 875,
      engine: 'K38-D(M)',
      cylinder: '12V',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C1000M',
      primeKW: 800,
      primeKVA: 1000,
      engine: 'K38-D(M)',
      cylinder: '12V',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
    {
      model: 'GW-C1188M',
      primeKW: 950,
      primeKVA: 1188,
      engine: 'K38-D(M)',
      cylinder: '12V',
      speedGovernor: 'E',
      displacement: '38.0 ',
      cons: 'N/A',
      emission: 'IMO2',
    },
  ]
})
