export default defineEventHandler(() => {
  return [
    {
      model: 'GW-S125M',
      primeKW: 100,
      primeKVA: 125,
      engine: 'SC4H165.15CF2',
      cylinder: '4',
      speedGovernor: 'E',
      displacement: 4.3,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S150M',
      primeKW: 120,
      primeKVA: 150,
      engine: 'SC7H200.15CF2',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 6.5,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S188M',
      primeKW: 150,
      primeKVA: 188,
      engine: 'SC7H230.15CF2',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 6.5,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S225M',
      primeKW: 180,
      primeKVA: 225,
      engine: 'SC9D260.15CF2',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 8.9,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S250M',
      primeKW: 200,
      primeKVA: 250,
      engine: 'SC9D310.15CF2',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 8.9,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S313M',
      primeKW: 250,
      primeKVA: 313,
      engine: 'SC12E410.15CF2',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 11.8,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S350M',
      primeKW: 280,
      primeKVA: 350,
      engine: 'SC15G420.15CF1',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 14.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S375M',
      primeKW: 300,
      primeKVA: 375,
      engine: 'SC15G480.15CF1',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 14.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S450M',
      primeKW: 360,
      primeKVA: 450,
      engine: 'SC25K570.15CF1',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 25.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S500M',
      primeKW: 400,
      primeKVA: 500,
      engine: 'SC25K650.15CF1',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 25.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S563M',
      primeKW: 450,
      primeKVA: 563,
      engine: 'SC25K730.15CF1',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 25.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S625M',
      primeKW: 500,
      primeKVA: 625,
      engine: 'SC25K820.15CF1',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 25.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
    {
      model: 'GW-S750M',
      primeKW: 600,
      primeKVA: 750,
      engine: 'SC25K900.15CF21',
      cylinder: '6L',
      speedGovernor: 'E',
      displacement: 25.2,
      cons: 'N/A',
      emission: 'CHINA 2',
    },
  ]
})
